# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='tel',
            field=models.IntegerField(null=True, verbose_name='\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=20, verbose_name='\u7528\u6237\u540d'),
        ),
    ]
