# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_auto_20171130_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='age',
            field=models.IntegerField(null=True, verbose_name='\u5e74\u9f84'),
        ),
        migrations.AlterField(
            model_name='test',
            name='tel',
            field=models.CharField(max_length=11, null=True, verbose_name='\u7535\u8bdd'),
        ),
    ]
