# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_auto_20171201_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='test')),
                ('foreignId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.Test')),
            ],
        ),
    ]
